# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e26868705cf5fe3e126c893cec75509ea38686d897ad175c17cfe757f8a681df6f39467249180af547cd0cf7649c3e2c72119c0ca5696a5e2d107955a2483e3

test:
  secret_key_base: f014d7373a8a79a5a43ab4f5de66c05d3126004f78c92e98c03a0e16b0cbc4ed031ba40e1eab8cc75ab562e9c3c22ed9c25ca45f63c619304a6a6764f20d5753

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
